server:
  port: 8081

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: Pp123456@#
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
