server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/theater_db
    username: root
    password: Pp123456@#
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
